In [1]:
import numpy as np
import os
import pandas as pd
import torch
import numpy.random as rand
from data import *

# load data for testing

In [2]:
path = "./data/"

In [3]:
human = np.load(path + 'human_feats.npy')
virus = np.load(path + 'virus_feats.npy')

In [4]:
human[0].shape

(2799,)

In [5]:
interactions = pd.read_csv(path + 't1_train.csv')

In [6]:
interactions.head()

node1  node2  edge
0    151   2841     1
1    151   2874     1
2    151    780     1
3    151   1183     1
4    155   2346     1

In [7]:
pool = interactions.loc[interactions['edge'] == 1].index.values

## test create_data_loader

In [8]:
gen = SingleTaskGenerator(interactions, human, virus, .80)

In [9]:
dl = gen.create_loader(3)

In [10]:
next(iter(dl))

[tensor([[0.9744, 0.8462, 0.4103,  ..., 0.0000, 0.0000, 1.0000],
         [0.0000, 0.1667, 0.0000,  ..., 0.0000, 0.0000, 1.0000],
         [0.9744, 0.8462, 0.4103,  ..., 0.0000, 0.0000, 1.0000]],
        dtype=torch.float64),
 tensor([[0.8667, 0.5333, 0.4000,  ..., 0.0000, 0.0000, 1.0000],
         [0.8667, 0.5333, 0.4000,  ..., 0.0000, 0.0000, 1.0000],
         [0.8667, 0.5333, 0.4000,  ..., 0.0000, 0.0000, 1.0000]],
        dtype=torch.float64),
 tensor([187, 330, 328]),
 tensor([1255, 1592, 1255])]