In [7]:
import numpy as np
import os
import pandas as pd
import torch
import numpy.random as rand
from data import *

# load data for testing

In [8]:
path = "./data/"

In [9]:
human = np.load(path + 'human_feats.npy')
virus = np.load(path + 'virus_feats.npy')

In [10]:
human[:5, :5], virus[:5,:5]

(array([[0.2581 , 0.3226 , 0.3226 , 0.     , 0.06452],
        [0.2381 , 0.619  , 0.3333 , 0.2381 , 0.09524],
        [0.25   , 0.3333 , 0.9167 , 0.5    , 0.25   ],
        [0.7143 , 0.5238 , 0.9524 , 0.2381 , 0.04762],
        [0.2727 , 0.4545 , 0.2273 , 0.09091, 0.5    ]]),
 array([[0.9615 , 0.6154 , 0.8846 , 0.4231 , 0.5769 ],
        [0.2273 , 0.5303 , 0.07576, 0.0303 , 0.     ],
        [0.7589 , 0.7768 , 0.9196 , 0.3393 , 0.4911 ],
        [0.9924 , 0.4697 , 0.4091 , 0.2121 , 0.2273 ],
        [0.6897 , 0.5517 , 0.931  , 0.3793 , 0.5172 ]]))

In [11]:
interactions = pd.read_csv(path + 't1_train.csv')

In [12]:
interactions.head()

node1  node2  edge
0    151   2841     1
1    151   2874     1
2    151    780     1
3    151   1183     1
4    155   2346     1

In [13]:
pool = interactions.loc[interactions['edge'] == 1].index.values

## test create_data_loader

In [14]:
gen = SingleTaskGenerator(interactions, human, virus, .80)

In [15]:
dl = gen.create_data_loader(24)

In [16]:
next(iter(dl))

[tensor([[0.8889, 0.9778, 0.8222,  ..., 0.0000, 0.0000, 1.0000],
         [0.2727, 0.9091, 0.7273,  ..., 0.0000, 0.0000, 1.0000],
         [0.7755, 0.7653, 0.3673,  ..., 0.0000, 0.0000, 1.0000],
         ...,
         [0.9750, 0.6250, 0.4000,  ..., 0.0000, 0.0000, 1.0000],
         [0.9744, 0.8462, 0.4103,  ..., 0.0000, 0.0000, 1.0000],
         [0.9750, 0.6250, 0.4000,  ..., 0.0000, 0.0000, 1.0000]],
        dtype=torch.float64),
 tensor([[0.2000, 0.6000, 0.4500,  ..., 0.0000, 0.0000, 1.0000],
         [0.2590, 0.5361, 0.4639,  ..., 0.0000, 0.0000, 1.0000],
         [0.2000, 0.4000, 0.0000,  ..., 0.0000, 0.0000, 1.0000],
         ...,
         [0.8667, 0.5333, 0.4000,  ..., 0.0000, 0.0000, 1.0000],
         [0.8667, 0.5333, 0.4000,  ..., 0.0000, 0.0000, 1.0000],
         [0.8667, 0.5333, 0.4000,  ..., 0.0000, 0.0000, 1.0000]],
        dtype=torch.float64),
 tensor([888,   2, 829, 878, 825,   3, 899, 809, 864, 838, 852, 844, 873, 848,
         831,   5, 855, 819, 847, 894, 840, 893, 85