In [1]:
import numpy as np


In [5]:
USE_GPU = True

if USE_GPU and torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')

print_every = 100

print('using device:', device)

using device: cuda


In [14]:
class MatrixFactorization(torch.nn.Module):
    
    def __init__(self, n_users, n_items, n_factors=20):
        super().__init__()
        self.user_factors = torch.nn.Embedding(n_users, 
                                               n_factors,
                                               sparse=True)
        self.item_factors = torch.nn.Embedding(n_items, 
                                               n_factors,
                                               sparse=True)
        
    def forward(self, user, item):
        print(self.user_factors(user).shape, self.item_factors(item).shape)
        return (self.user_factors(user) * self.item_factors(item)).sum(1)

In [15]:
model = MatrixFactorization(n_users, n_items, n_factors=20)
loss_func = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), 
                            lr=1e-6) # learning rate

In [16]:
# Sort our data
rows, cols = ratings.nonzero()
p = np.random.permutation(len(rows))
rows, cols = rows[p], cols[p]

for row, col in zip(*(rows, cols)):
    # Turn data into variables
    rating = Variable(torch.FloatTensor([ratings[row, col]]))
    row = Variable(torch.LongTensor([np.long(row)]))
    col = Variable(torch.LongTensor([np.long(col)]))
    print(row, col)
    
    # Predict and calculate loss
    prediction = model(row, col)
    loss = loss_func(prediction, rating)
    
    # Backpropagate
    loss.backward()
    
    # Update the parameters
    optimizer.step()

tensor([810]) tensor([944])
torch.Size([1, 20]) torch.Size([1, 20])
tensor([687]) tensor([126])
torch.Size([1, 20]) torch.Size([1, 20])
tensor([81]) tensor([341])
torch.Size([1, 20]) torch.Size([1, 20])
tensor([614]) tensor([93])
torch.Size([1, 20]) torch.Size([1, 20])
tensor([146]) tensor([517])
torch.Size([1, 20]) torch.Size([1, 20])
tensor([388]) tensor([770])
torch.Size([1, 20]) torch.Size([1, 20])
tensor([387]) tensor([188])
torch.Size([1, 20]) torch.Size([1, 20])
tensor([774]) tensor([311])
torch.Size([1, 20]) torch.Size([1, 20])
tensor([728]) tensor([147])
torch.Size([1, 20]) torch.Size([1, 20])
tensor([719]) tensor([153])
torch.Size([1, 20]) torch.Size([1, 20])
tensor([333]) tensor([908])
torch.Size([1, 20]) torch.Size([1, 20])
tensor([396]) tensor([130])
torch.Size([1, 20]) torch.Size([1, 20])
tensor([423]) tensor([9])
torch.Size([1, 20]) torch.Size([1, 20])
tensor([108]) tensor([441])
torch.Size([1, 20]) torch.Size([1, 20])
tensor([854]) tensor([531])
torch.Size([1, 20]) torc

KeyboardInterrupt: 