In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

# Check if we can just randomly split data

The train matrix is pretty sparse so let's see if enough positives are being counted if we randomly split or if we need to do something special to make sure we're training on enough positives/negatives.

Statistically it should be good but it doesn't hurt to make sure.

In [6]:
train = pd.read_csv('t1_train.csv')
train.head()

node1  node2  edge
0    151   2841     1
1    151   2874     1
2    151    780     1
3    151   1183     1
4    155   2346     1

In [16]:
X = train.drop(['edge'], axis=1).values
y = train.drop(['node1', 'node2'], axis=1).values
print('X: \n', X,'\ny: \n', y)

X: 
 [[ 151 2841]
 [ 151 2874]
 [ 151  780]
 ...
 [ 309 5866]
 [ 623 3642]
 [ 299 3528]] 
y: 
 [[1]
 [1]
 [1]
 ...
 [0]
 [0]
 [0]]


In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.30, random_state=42)

In [22]:
y_train[y_train==1], len(y_train[y_train==1])

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), 80)

In [23]:
y_test[y_test==1], len(y_test[y_test==1])

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1]), 26)

In [24]:
len(y[y==1])

106

# Let's check for the others and the combined set

In [54]:
def ct_pos_ran_split(d):
#     all = d['']
    X = d.drop(['edge'], axis=1).values
    y = d['edge'].values
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.30, random_state=42)
    

    print('total positives: ', len(y[y==1]))
    print('n: ', len(y))
    print('density: ', len(y[y==1])/len(y))
    print('positives in y_train: ', len(y_train[y_train==1]))
    print('positives in y_test: ', len(y_test[y_test==1]))

In [55]:
t1 = pd.read_csv('t1_train.csv')
t2 = pd.read_csv('t2_train.csv')
t3 = pd.read_csv('t3_train.csv')
comb = pd.read_csv('train.csv')

for d in [t1,t2,t3,comb]:
    ct_pos_ran_split(d)
    print()

total positives:  106
n:  9305
density:  0.01139172487909726
positives in y_train:  80
positives in y_test:  26

total positives:  0
n:  1064
density:  0.0
positives in y_train:  0
positives in y_test:  0

total positives:  84
n:  8820
density:  0.009523809523809525
positives in y_train:  60
positives in y_test:  24

total positives:  190
n:  19190
density:  0.009900990099009901
positives in y_train:  149
positives in y_test:  41



In [39]:
len(train)

9305

fishy....

# debugging our csvs

In [44]:
t = pd.read_csv('old_data/train.txt', sep=' ')

In [45]:
t.head()

node1  node2  edge
0    151   2841     1
1    151   2874     1
2    151    780     1
3    151   1183     1
4    155   2346     1

In [46]:
len(t)

19190

In [50]:
trainvals = t.values

In [53]:
len(trainvals[:9305])

9305

In [56]:
len(trainvals[9305:103370])

9885

In [57]:
t2 = trainvals[9305:103370]

In [62]:
edges = t2[:,2]
edges[edges==1]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [59]:
trainvals[9305]

array([ 257, 4783,    0])

looks like we did something wrong when creating the csvs :(